trigger:
  branches:
    include:
    - none
stages:
- stage: __default
  jobs:
  - job: Job
    # pool:
    #   name: 'Self-Hosted'
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          # Checking Chrome version
          try {
              Write-Host "Checking Chrome version..."
              $chromeVersion = ((Get-Item "C:\Program Files\Google\Chrome\Application\chrome.exe").VersionInfo).ProductVersion
              Write-Host $chromeVersion
          }
          catch {
              Write-Host "Chrome is not installed."
          }
          # selenium
          try {
              Write-Host "selenium..."
              pip install selenium
          }
          catch {
              Write-Host "selenium is not installed."
          }
    # - task: SonarQubePrepare@5
    #   inputs:
    #     SonarQube: 'sq-concourse'
    #     scannerMode: 'Other'
    #     extraProperties: |
    #       sonar.projectKey=Concourse_Concourse_MRO_QA_InWork_AYRY-HoTirE7NF2OWLTK
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          # Executing batch file - MavenCMD
          try {
              Write-Host "Starting MavenCMD..."
              .\MavenCMD.bat
          }
          catch {
              Write-Host "MavenCMD Failed."
          }
        workingDirectory: '$(Build.SourcesDirectory)\paperlessMROAutomation'
      displayName: 'Executing MavenCMD'
    # - task: SonarQubePublish@5
    #   inputs:
    #     pollingTimeoutSec: '300'
    - task: PublishBuildArtifacts@1
      inputs:
        ArtifactName: 'drop'
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'

